import "@/styles/globals.css";
import { DM_Sans as FontSans } from "next/font/google";

const fontSans = FontSans({ subsets: ["latin"] });

export const metadata = {
  title: "Eventmakers",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontSans.className}>{children}</body>
    </html>
  );
}
